// rv32i_core.sv
// The RV32I core, exactly as generated by Makerchip (top.sv), but modified
// so that QSPI-facing signals are genuine module ports instead of being
// wired to internally-instantiated QSPI modules. This lets the core be
// instantiated as a standalone component alongside separate qspi_controller.v,
// rv32i_qspi_mem.v, and sim_qspi_pmod.v files, wired together by an external
// top-level module (qspi_soc_top.sv).



// For silencing unused signal messages.
`define BOGUS_USE(ignore)

module rv32i_core (
    input  wire        clk,
    input  wire        reset,
    input  wire [31:0] cyc_cnt,
    output wire         passed,
    output wire         failed,

    // Instruction fetch interface (to rv32i_qspi_mem, externally instantiated)

    output wire [23:0] i_addr,
    output wire         i_req,
    input  wire [31:0] i_rdata,
    input  wire         i_ready,

    // Data read/write interface (to rv32i_qspi_mem, externally instantiated)

    output wire [24:0] d_addr,
    output wire         d_req,
    output wire         d_we,
    output wire  [3:0] d_wstrb,
    output wire [31:0] d_wdata,
    input  wire [31:0] d_rdata,
    input  wire         d_ready
);
    /* verilator lint_save */ /* verilator lint_off UNOPTFLAT */
    bit [256:0] RW_rand_raw;
    bit [256+63:0] RW_rand_vect;
    pseudo_rand #(.WIDTH(257)) pseudo_rand (clk, reset, RW_rand_raw[256:0]);
    assign RW_rand_vect[256+63:0] = {RW_rand_raw[62:0], RW_rand_raw};
    /* verilator lint_restore */
    /* verilator lint_off WIDTH */ /* verilator lint_off UNOPTFLAT */
    /* verilator lint_on WIDTH */

    // Internal wires — these carry the memory-module's responses into the
    // core's TLV-generated logic below (same names the TLV logic already
    // expects, so the generated logic itself needs zero changes).
    wire [31:0] mem_i_rdata_w = i_rdata;
    wire        mem_i_ready_w = i_ready;
    wire [31:0] mem_d_rdata_w = d_rdata;
    wire        mem_d_ready_w = d_ready;

`include "top_gen.sv"

    // ================================================================
    // TLV-generated core logic — UNCHANGED from the Makerchip output.
   

    assign L0_reset_a0 = reset;

    // ---- QSPI stall FSM ----
    assign L0_state_a0[1:0] = L0_reset_a0 ? 2'd0 : (L0_reset_a1 ? 2'd0 : L0_next_state_a1);
    assign L0_next_state_a0[1:0] =
       (L0_state_a0 == 2'd0) ? 2'd1 :
       (L0_state_a0 == 2'd1) ? (mem_i_ready_w ? (L0_is_mem_op_a0 ? 2'd2 : 2'd0) : 2'd1) :
       (L0_state_a0 == 2'd2) ? 2'd3 :
       (L0_state_a0 == 2'd3) ? (mem_d_ready_w ? 2'd0 : 2'd3) :
                           2'd0;

    assign L0_i_req_a0 = (L0_state_a0 == 2'd0) && !L0_reset_a0;
    assign L0_d_req_a0 = (L0_state_a0 == 2'd2) && !L0_reset_a0;

    assign L0_instr_a0[31:0] = L0_reset_a0 ? 32'b0 :
                   ((L0_state_a0 == 2'd1) && mem_i_ready_w) ? mem_i_rdata_w :
                   L0_instr_a1;

    assign L0_is_mem_op_a0 = L0_is_load_a0 || L0_is_store_a0;

    assign L0_commit_a0 = ((L0_state_a0 == 2'd1) && mem_i_ready_w && !L0_is_mem_op_a0) ||
              ((L0_state_a0 == 2'd3) && mem_d_ready_w);

    assign L0_pc_a0[31:0] = L0_reset_a0 ? 32'b0 :
                (L0_reset_a1 ? 32'b0 :
                (L0_commit_a1 ? L0_next_pc_a1 : L0_pc_a1));

    assign L0_next_pc_a0[31:0] = L0_is_trap_a0 ? L0_pc_a0 :
                            L0_taken_br_a0 ? L0_br_tgt_pc_a0 :
                            L0_is_jal_a0  ? L0_br_tgt_pc_a0 :
                            L0_is_jalr_a0 ? L0_jalr_tgt_pc_a0 :
                                       (L0_pc_a0 + 32'd4);

    assign L0_i_addr_a0[23:0] = L0_pc_a0[23:0];

    // DECODE Logic (Instr Type)
    assign L0_is_u_instr_a0 = L0_instr_a0[6:2] ==? 5'b0x101;
    assign L0_is_i_instr_a0 = L0_instr_a0[6:2] ==? 5'b0000x ||
                  L0_instr_a0[6:2] ==? 5'b001x0 ||
                  L0_instr_a0[6:2] ==? 5'b11001;
    assign L0_is_r_instr_a0 = L0_instr_a0[6:2] ==? 5'b011x0;
    assign L0_is_s_instr_a0 = L0_instr_a0[6:2] ==? 5'b0100x;
    assign L0_is_b_instr_a0 = L0_instr_a0[6:2] ==? 5'b11000;
    assign L0_is_j_instr_a0 = L0_instr_a0[6:2] ==? 5'b11011;

    // DECODE Logic (Instr Fields)
    assign L0_opcode_a0[6:0] = L0_instr_a0[6:0];
    assign L0_rd_a0[4:0] = L0_instr_a0[11:7];
    assign L0_funct3_a0[2:0] = L0_instr_a0[14:12];
    assign L0_rs1_a0[4:0] = L0_instr_a0[19:15];
    assign L0_rs2_a0[4:0] = L0_instr_a0[24:20];

    assign L0_rd_valid_a0 = L0_is_r_instr_a0 || L0_is_i_instr_a0 || L0_is_u_instr_a0 || L0_is_j_instr_a0 || L0_is_csr_a0;
    assign L0_funct3_valid_a0 = L0_is_r_instr_a0 || L0_is_i_instr_a0 || L0_is_s_instr_a0 || L0_is_b_instr_a0;
    assign L0_rs1_valid_a0 = L0_is_r_instr_a0 || L0_is_i_instr_a0 || L0_is_s_instr_a0 || L0_is_b_instr_a0 || L0_is_csr_a0;
    assign L0_rs2_valid_a0 = L0_is_r_instr_a0 || L0_is_s_instr_a0 || L0_is_b_instr_a0;
    assign L0_imm_valid_a0 = L0_is_i_instr_a0 || L0_is_s_instr_a0 || L0_is_b_instr_a0 || L0_is_u_instr_a0 || L0_is_j_instr_a0;

    assign L0_imm_a0[31:0] = L0_is_i_instr_a0 ? {{21{L0_instr_a0[31]}}, L0_instr_a0[30:20]} :
                 L0_is_s_instr_a0 ? {{21{L0_instr_a0[31]}}, L0_instr_a0[11:7], L0_instr_a0[30:25]} :
                 L0_is_b_instr_a0 ? {{20{L0_instr_a0[31]}}, L0_instr_a0[7], L0_instr_a0[30:25], L0_instr_a0[11:8], 1'b0} :
                 L0_is_u_instr_a0 ? {L0_instr_a0[31], L0_instr_a0[30:12], 12'b0} :
                 L0_is_j_instr_a0 ? {{12{L0_instr_a0[31]}}, L0_instr_a0[19:12], L0_instr_a0[20], L0_instr_a0[30:21], 1'b0} :
                 32'b0;

    // DECODE Logic (Instr)
    assign L0_dec_bits_a0[10:0] = {L0_instr_a0[30], L0_funct3_a0, L0_opcode_a0};
    assign L0_is_addi_a0 = L0_dec_bits_a0 ==? 11'bx_000_0010011;
    assign L0_is_add_a0  = L0_dec_bits_a0 ==? 11'b0_000_0110011;
    assign L0_is_beq_a0  = L0_dec_bits_a0 ==? 11'bx_000_1100011;
    assign L0_is_bne_a0  = L0_dec_bits_a0 ==? 11'bx_001_1100011;
    assign L0_is_blt_a0  = L0_dec_bits_a0 ==? 11'bx_100_1100011;
    assign L0_is_bge_a0  = L0_dec_bits_a0 ==? 11'bx_101_1100011;
    assign L0_is_bltu_a0 = L0_dec_bits_a0 ==? 11'bx_110_1100011;
    assign L0_is_bgeu_a0 = L0_dec_bits_a0 ==? 11'bx_111_1100011;

    assign L0_is_sub_a0  = L0_dec_bits_a0 ==? 11'b1_000_0110011;
    assign L0_is_sll_a0  = L0_dec_bits_a0 ==? 11'b0_001_0110011;
    assign L0_is_slt_a0  = L0_dec_bits_a0 ==? 11'b0_010_0110011;
    assign L0_is_sltu_a0 = L0_dec_bits_a0 ==? 11'b0_011_0110011;
    assign L0_is_xor_a0  = L0_dec_bits_a0 ==? 11'b0_100_0110011;
    assign L0_is_srl_a0  = L0_dec_bits_a0 ==? 11'b0_101_0110011;
    assign L0_is_sra_a0  = L0_dec_bits_a0 ==? 11'b1_101_0110011;
    assign L0_is_or_a0   = L0_dec_bits_a0 ==? 11'b0_110_0110011;
    assign L0_is_and_a0  = L0_dec_bits_a0 ==? 11'b0_111_0110011;

    assign L0_is_slti_a0  = L0_dec_bits_a0 ==? 11'bx_010_0010011;
    assign L0_is_sltiu_a0 = L0_dec_bits_a0 ==? 11'bx_011_0010011;
    assign L0_is_xori_a0  = L0_dec_bits_a0 ==? 11'bx_100_0010011;
    assign L0_is_ori_a0   = L0_dec_bits_a0 ==? 11'bx_110_0010011;
    assign L0_is_andi_a0  = L0_dec_bits_a0 ==? 11'bx_111_0010011;
    assign L0_is_slli_a0  = L0_dec_bits_a0 ==? 11'b0_001_0010011;
    assign L0_is_srli_a0  = L0_dec_bits_a0 ==? 11'b0_101_0010011;
    assign L0_is_srai_a0  = L0_dec_bits_a0 ==? 11'b1_101_0010011;

    assign L0_is_lb_a0  = L0_dec_bits_a0 ==? 11'bx_000_0000011;
    assign L0_is_lh_a0  = L0_dec_bits_a0 ==? 11'bx_001_0000011;
    assign L0_is_lw_a0  = L0_dec_bits_a0 ==? 11'bx_010_0000011;
    assign L0_is_lbu_a0 = L0_dec_bits_a0 ==? 11'bx_100_0000011;
    assign L0_is_lhu_a0 = L0_dec_bits_a0 ==? 11'bx_101_0000011;
    assign L0_is_load_a0 = L0_is_lb_a0 || L0_is_lh_a0 || L0_is_lw_a0 || L0_is_lbu_a0 || L0_is_lhu_a0;

    assign L0_is_sb_a0 = L0_dec_bits_a0 ==? 11'bx_000_0100011;
    assign L0_is_sh_a0 = L0_dec_bits_a0 ==? 11'bx_001_0100011;
    assign L0_is_sw_a0 = L0_dec_bits_a0 ==? 11'bx_010_0100011;
    assign L0_is_store_a0 = L0_is_sb_a0 || L0_is_sh_a0 || L0_is_sw_a0;

    assign L0_is_lui_a0   = L0_opcode_a0 ==? 7'b0110111;
    assign L0_is_auipc_a0 = L0_opcode_a0 ==? 7'b0010111;

    assign L0_is_jal_a0  = L0_opcode_a0 ==? 7'b1101111;
    assign L0_is_jalr_a0 = (L0_opcode_a0 ==? 7'b1100111) && (L0_funct3_a0 == 3'b000);
    assign L0_jalr_tgt_pc_a0[31:0] = (L0_src1_value_a0 + L0_imm_a0) & 32'hFFFFFFFE;

    assign L0_is_system_a0 = L0_opcode_a0 ==? 7'b1110011;
    assign L0_is_ecall_a0  = L0_is_system_a0 && (L0_funct3_a0==3'b000) && (L0_instr_a0[31:20]==12'b0);
    assign L0_is_ebreak_a0 = L0_is_system_a0 && (L0_funct3_a0==3'b000) && (L0_instr_a0[31:20]==12'b1);
    assign L0_is_csrrw_a0  = L0_is_system_a0 && (L0_funct3_a0==3'b001);
    assign L0_is_csrrs_a0  = L0_is_system_a0 && (L0_funct3_a0==3'b010);
    assign L0_is_csrrc_a0  = L0_is_system_a0 && (L0_funct3_a0==3'b011);
    assign L0_is_csrrwi_a0 = L0_is_system_a0 && (L0_funct3_a0==3'b101);
    assign L0_is_csrrsi_a0 = L0_is_system_a0 && (L0_funct3_a0==3'b110);
    assign L0_is_csrrci_a0 = L0_is_system_a0 && (L0_funct3_a0==3'b111);
    assign L0_is_csr_a0    = L0_is_csrrw_a0 || L0_is_csrrs_a0 || L0_is_csrrc_a0 || L0_is_csrrwi_a0 || L0_is_csrrsi_a0 || L0_is_csrrci_a0;
    assign L0_is_fence_a0  = L0_opcode_a0 ==? 7'b0001111;
    assign L0_is_trap_a0   = L0_is_ecall_a0 || L0_is_ebreak_a0;

    assign L0_csr_addr_a0[4:0] = L0_instr_a0[24:20];
    assign L0_csr_operand_a0[31:0] = (L0_is_csrrwi_a0 || L0_is_csrrsi_a0 || L0_is_csrrci_a0) ? {27'b0, L0_rs1_a0[4:0]} : L0_src1_value_a0;
    assign L0_csr_new_value_a0[31:0] = (L0_is_csrrw_a0 || L0_is_csrrwi_a0) ? L0_csr_operand_a0 :
                            (L0_is_csrrs_a0 || L0_is_csrrsi_a0) ? (L0_csr_old_value_a0 | L0_csr_operand_a0) :
                                                         (L0_csr_old_value_a0 & ~L0_csr_operand_a0);

    // ---- QSPI data-side wiring ----
    assign L0_ld_st_addr_a0[31:0] = L0_src1_value_a0 + L0_imm_a0;
    assign L0_byte_offset_a0[1:0] = L0_ld_st_addr_a0[1:0];

    assign L0_d_addr_a0[24:0] = L0_ld_st_addr_a0[24:0];
    assign L0_d_we_a0 = L0_is_store_a0;

    assign L0_d_wstrb_a0[3:0] =
       (L0_is_lb_a0 || L0_is_lbu_a0 || L0_is_sb_a0) ? (4'b0001 << L0_byte_offset_a0) :
       (L0_is_lh_a0 || L0_is_lhu_a0 || L0_is_sh_a0) ? (4'b0011 << {L0_byte_offset_a0[1], 1'b0}) :
       (L0_is_lw_a0 || L0_is_sw_a0)            ? 4'b1111 :
                                        4'b0000;

    assign L0_d_wdata_a0[31:0] = L0_is_sb_a0 ? {4{L0_src2_value_a0[7:0]}} :
                      L0_is_sh_a0 ? {2{L0_src2_value_a0[15:0]}} :
                               L0_src2_value_a0;

    // ALU
    assign L0_result_a0[31:0] = L0_is_addi_a0 ? L0_src1_value_a0 + L0_imm_a0 :
                    L0_is_add_a0  ? L0_src1_value_a0 + L0_src2_value_a0 :
                    L0_is_sub_a0  ? L0_src1_value_a0 - L0_src2_value_a0 :
                    L0_is_sll_a0  ? L0_src1_value_a0 << L0_src2_value_a0[4:0] :
                    L0_is_slt_a0  ? {31'b0, (L0_src1_value_a0[31] != L0_src2_value_a0[31]) ? L0_src1_value_a0[31] : (L0_src1_value_a0 < L0_src2_value_a0)} :
                    L0_is_sltu_a0 ? {31'b0, L0_src1_value_a0 < L0_src2_value_a0} :
                    L0_is_xor_a0  ? L0_src1_value_a0 ^ L0_src2_value_a0 :
                    L0_is_srl_a0  ? L0_src1_value_a0 >> L0_src2_value_a0[4:0] :
                    L0_is_sra_a0  ? (L0_src1_value_a0[31] ? ~((~L0_src1_value_a0) >> L0_src2_value_a0[4:0]) : (L0_src1_value_a0 >> L0_src2_value_a0[4:0])) :
                    L0_is_or_a0   ? L0_src1_value_a0 | L0_src2_value_a0 :
                    L0_is_and_a0  ? L0_src1_value_a0 & L0_src2_value_a0 :
                    L0_is_slti_a0  ? {31'b0, (L0_src1_value_a0[31] != L0_imm_a0[31]) ? L0_src1_value_a0[31] : (L0_src1_value_a0 < L0_imm_a0)} :
                    L0_is_sltiu_a0 ? {31'b0, L0_src1_value_a0 < L0_imm_a0} :
                    L0_is_xori_a0  ? L0_src1_value_a0 ^ L0_imm_a0 :
                    L0_is_ori_a0   ? L0_src1_value_a0 | L0_imm_a0 :
                    L0_is_andi_a0  ? L0_src1_value_a0 & L0_imm_a0 :
                    L0_is_slli_a0  ? L0_src1_value_a0 << L0_imm_a0[4:0] :
                    L0_is_srli_a0  ? L0_src1_value_a0 >> L0_imm_a0[4:0] :
                    L0_is_srai_a0  ? (L0_src1_value_a0[31] ? ~((~L0_src1_value_a0) >> L0_imm_a0[4:0]) : (L0_src1_value_a0 >> L0_imm_a0[4:0])) :
                    L0_is_lui_a0   ? L0_imm_a0 :
                    L0_is_auipc_a0 ? L0_pc_a0 + L0_imm_a0 :
                    L0_is_lw_a0    ? mem_d_rdata_w :
                    L0_is_lb_a0    ? {{24{mem_d_rdata_w[7]}}, mem_d_rdata_w[7:0]} :
                    L0_is_lbu_a0   ? {24'b0, mem_d_rdata_w[7:0]} :
                    L0_is_lh_a0    ? {{16{mem_d_rdata_w[15]}}, mem_d_rdata_w[15:0]} :
                    L0_is_lhu_a0   ? {16'b0, mem_d_rdata_w[15:0]} :
                    L0_is_jal_a0   ? L0_pc_a0 + 32'd4 :
                    L0_is_jalr_a0  ? L0_pc_a0 + 32'd4 :
                    L0_is_csr_a0   ? L0_csr_old_value_a0 :
                    32'b0;

    // Register File Write
    assign L0_wr_index_a0[4:0] = L0_rd_a0;
    assign L0_wr_data_a0[31:0] = L0_result_a0;
    assign L0_wr_en_a0 = (L0_is_r_instr_a0 ||
             L0_is_i_instr_a0 ||
             L0_is_u_instr_a0 ||
             L0_is_j_instr_a0 ||
             L0_is_csr_a0)
         && (L0_rd_a0 != 5'd0)
         && L0_commit_a0;

    // Branch Logic
    assign L0_taken_br_a0 = L0_is_beq_a0 ? (L0_src1_value_a0 == L0_src2_value_a0) :
                L0_is_bne_a0 ? (L0_src1_value_a0 != L0_src2_value_a0) :
                L0_is_blt_a0 ? (L0_src1_value_a0 < L0_src2_value_a0) :
                L0_is_bge_a0 ? (L0_src1_value_a0 >= L0_src2_value_a0) :
                L0_is_bltu_a0 ? (L0_src1_value_a0 <  L0_src2_value_a0) :
                L0_is_bgeu_a0 ? (L0_src1_value_a0 >= L0_src2_value_a0) :
                           1'b0;
    assign L0_br_tgt_pc_a0[31:0] = L0_pc_a0 + L0_imm_a0;

    // CSR register bank
    assign L0_csr_wr_en_a0 = L0_is_csr_a0 && !L0_reset_a0 && L0_commit_a0;
    for (csr = 0; csr <= 31; csr++) begin : L1_Csr logic L1_csr_wr_a0;
       assign L1_csr_wr_a0 = L0_csr_wr_en_a0 && (L0_csr_addr_a0 == csr);
       assign Csr_value_n1[csr][31:0] = L0_reset_a0 ? 32'b0 : (L1_csr_wr_a0 ? L0_csr_new_value_a0 : Csr_value_a0[csr][31:0]); end
    assign L0_csr_old_value_a0[31:0] = Csr_value_a0[L0_csr_addr_a0];

    `BOGUS_USE(L0_is_store_a0 L0_rd_valid_a0 L0_funct3_valid_a0 L0_imm_valid_a0 L0_is_fence_a0 L0_is_ebreak_a0)

    assign L0_passed_cond_a0 = (Xreg_value_a0[30] == 32'b1) &&
                  (! L0_reset_a0 && L0_next_pc_a0[31:0] == L0_pc_a0[31:0]);
    assign passed = L0_passed_cond_a2;
    assign failed = cyc_cnt > 500;

    assign L0_rf1_wr_en_a0 = L0_wr_en_a0;
    assign L0_rf1_wr_index_a0[$clog2(32)-1:0]  = L0_wr_index_a0[4:0];
    assign L0_rf1_wr_data_a0[32-1:0] = L0_wr_data_a0[31:0];

    assign L0_rf1_rd_en1_a0 = L0_rs1_valid_a0;
    assign L0_rf1_rd_index1_a0[$clog2(32)-1:0] = L0_rs1_a0[4:0];

    assign L0_rf1_rd_en2_a0 = L0_rs2_valid_a0;
    assign L0_rf1_rd_index2_a0[$clog2(32)-1:0] = L0_rs2_a0[4:0];

    for (xreg = 0; xreg <= 31; xreg++) begin : L1_Xreg logic L1_wr_a0;
       assign L1_wr_a0 = L0_rf1_wr_en_a0 && (L0_rf1_wr_index_a0 == xreg);
       assign Xreg_value_n1[xreg][32-1:0] = L0_reset_a0 ? xreg              :
                                  L1_wr_a0      ? L0_rf1_wr_data_a0 :
                                             Xreg_value_a0[xreg][32-1:0]; end

    assign L0_src1_value_a0[32-1:0]  =  L0_rf1_rd_en1_a0 ? Xreg_value_a0[L0_rf1_rd_index1_a0] : 'X;
    assign L0_src2_value_a0[32-1:0]  =  L0_rf1_rd_en2_a0 ? Xreg_value_a0[L0_rf1_rd_index2_a0] : 'X;

    // ================================================================
    // Bridge core-driven signals to the module's actual output ports
    // (previously bridged to internal wires feeding an internally-
    // instantiated rv32i_qspi_mem; now those ports connect externally).
    // ================================================================
    assign i_addr  = L0_i_addr_a0;
    assign i_req   = L0_i_req_a0;
    assign d_addr  = L0_d_addr_a0;
    assign d_req   = L0_d_req_a0;
    assign d_we    = L0_d_we_a0;
    assign d_wstrb = L0_d_wstrb_a0;
    assign d_wdata = L0_d_wdata_a0;

endmodule

// Undefine macros defined by SandPiper (in "top_gen.sv").
`undef BOGUS_USE
