// Generated by SandPiper(TM) 1.14-2022/10/10-beta-Pro from Redwood EDA, LLC.
// (Installed here: /home/web/live-sandhosts/mono-v154/sandpiper/distro.)
// Redwood EDA, LLC does not claim intellectual property rights to this file and provides no warranty regarding its correctness or quality.


genvar csr, imem, xreg;


//
// Signals declared top-level.
//

// For $br_tgt_pc.
logic [31:0] L0_br_tgt_pc_a0;

// For $byte_offset.
logic [1:0] L0_byte_offset_a0;

// For $commit.
logic L0_commit_a0,
      L0_commit_a1;

// For $csr_addr.
logic [4:0] L0_csr_addr_a0;

// For $csr_new_value.
logic [31:0] L0_csr_new_value_a0;

// For $csr_old_value.
logic [31:0] L0_csr_old_value_a0;

// For $csr_operand.
logic [31:0] L0_csr_operand_a0;

// For $csr_wr_en.
logic L0_csr_wr_en_a0;

// For $d_addr.
logic [24:0] L0_d_addr_a0;

// For $d_req.
logic L0_d_req_a0;

// For $d_wdata.
logic [31:0] L0_d_wdata_a0;

// For $d_we.
logic L0_d_we_a0;

// For $d_wstrb.
logic [3:0] L0_d_wstrb_a0;

// For $dec_bits.
logic [10:0] L0_dec_bits_a0;

// For $funct3.
logic [2:0] L0_funct3_a0;

// For $funct3_valid.
logic L0_funct3_valid_a0;

// For $i_addr.
logic [23:0] L0_i_addr_a0;

// For $i_req.
logic L0_i_req_a0;

// For $imm.
logic [31:0] L0_imm_a0;

// For $imm_valid.
logic L0_imm_valid_a0;

// For $instr.
logic [31:0] L0_instr_a0,
             L0_instr_a1;

// For $is_add.
logic L0_is_add_a0;

// For $is_addi.
logic L0_is_addi_a0;

// For $is_and.
logic L0_is_and_a0;

// For $is_andi.
logic L0_is_andi_a0;

// For $is_auipc.
logic L0_is_auipc_a0;

// For $is_b_instr.
logic L0_is_b_instr_a0;

// For $is_beq.
logic L0_is_beq_a0;

// For $is_bge.
logic L0_is_bge_a0;

// For $is_bgeu.
logic L0_is_bgeu_a0;

// For $is_blt.
logic L0_is_blt_a0;

// For $is_bltu.
logic L0_is_bltu_a0;

// For $is_bne.
logic L0_is_bne_a0;

// For $is_csr.
logic L0_is_csr_a0;

// For $is_csrrc.
logic L0_is_csrrc_a0;

// For $is_csrrci.
logic L0_is_csrrci_a0;

// For $is_csrrs.
logic L0_is_csrrs_a0;

// For $is_csrrsi.
logic L0_is_csrrsi_a0;

// For $is_csrrw.
logic L0_is_csrrw_a0;

// For $is_csrrwi.
logic L0_is_csrrwi_a0;

// For $is_ebreak.
logic L0_is_ebreak_a0;

// For $is_ecall.
logic L0_is_ecall_a0;

// For $is_fence.
logic L0_is_fence_a0;

// For $is_i_instr.
logic L0_is_i_instr_a0;

// For $is_j_instr.
logic L0_is_j_instr_a0;

// For $is_jal.
logic L0_is_jal_a0;

// For $is_jalr.
logic L0_is_jalr_a0;

// For $is_lb.
logic L0_is_lb_a0;

// For $is_lbu.
logic L0_is_lbu_a0;

// For $is_lh.
logic L0_is_lh_a0;

// For $is_lhu.
logic L0_is_lhu_a0;

// For $is_load.
logic L0_is_load_a0;

// For $is_lui.
logic L0_is_lui_a0;

// For $is_lw.
logic L0_is_lw_a0;

// For $is_mem_op.
logic L0_is_mem_op_a0;

// For $is_or.
logic L0_is_or_a0;

// For $is_ori.
logic L0_is_ori_a0;

// For $is_r_instr.
logic L0_is_r_instr_a0;

// For $is_s_instr.
logic L0_is_s_instr_a0;

// For $is_sb.
logic L0_is_sb_a0;

// For $is_sh.
logic L0_is_sh_a0;

// For $is_sll.
logic L0_is_sll_a0;

// For $is_slli.
logic L0_is_slli_a0;

// For $is_slt.
logic L0_is_slt_a0;

// For $is_slti.
logic L0_is_slti_a0;

// For $is_sltiu.
logic L0_is_sltiu_a0;

// For $is_sltu.
logic L0_is_sltu_a0;

// For $is_sra.
logic L0_is_sra_a0;

// For $is_srai.
logic L0_is_srai_a0;

// For $is_srl.
logic L0_is_srl_a0;

// For $is_srli.
logic L0_is_srli_a0;

// For $is_store.
logic L0_is_store_a0;

// For $is_sub.
logic L0_is_sub_a0;

// For $is_sw.
logic L0_is_sw_a0;

// For $is_system.
logic L0_is_system_a0;

// For $is_trap.
logic L0_is_trap_a0;

// For $is_u_instr.
logic L0_is_u_instr_a0;

// For $is_xor.
logic L0_is_xor_a0;

// For $is_xori.
logic L0_is_xori_a0;

// For $jalr_tgt_pc.
logic [31:0] L0_jalr_tgt_pc_a0;

// For $ld_st_addr.
logic [31:0] L0_ld_st_addr_a0;

// For $next_pc.
logic [31:0] L0_next_pc_a0,
             L0_next_pc_a1;

// For $next_state.
logic [1:0] L0_next_state_a0,
            L0_next_state_a1;

// For $opcode.
logic [6:0] L0_opcode_a0;

// For $passed_cond.
logic L0_passed_cond_a0,
      L0_passed_cond_a1,
      L0_passed_cond_a2;

// For $pc.
logic [31:0] L0_pc_a0,
             L0_pc_a1;

// For $rd.
logic [4:0] L0_rd_a0;

// For $rd_valid.
logic L0_rd_valid_a0;

// For $reset.
logic L0_reset_a0,
      L0_reset_a1;

// For $result.
logic [31:0] L0_result_a0;

// For $rf1_rd_en1.
logic L0_rf1_rd_en1_a0;

// For $rf1_rd_en2.
logic L0_rf1_rd_en2_a0;

// For $rf1_rd_index1.
logic [$clog2(32)-1:0] L0_rf1_rd_index1_a0;

// For $rf1_rd_index2.
logic [$clog2(32)-1:0] L0_rf1_rd_index2_a0;

// For $rf1_wr_data.
logic [32-1:0] L0_rf1_wr_data_a0;

// For $rf1_wr_en.
logic L0_rf1_wr_en_a0;

// For $rf1_wr_index.
logic [$clog2(32)-1:0] L0_rf1_wr_index_a0;

// For $rs1.
logic [4:0] L0_rs1_a0;

// For $rs1_valid.
logic L0_rs1_valid_a0;

// For $rs2.
logic [4:0] L0_rs2_a0;

// For $rs2_valid.
logic L0_rs2_valid_a0;

// For $src1_value.
logic [32-1:0] L0_src1_value_a0;

// For $src2_value.
logic [32-1:0] L0_src2_value_a0;

// For $state.
logic [1:0] L0_state_a0;

// For $taken_br.
logic L0_taken_br_a0;

// For $wr_data.
logic [31:0] L0_wr_data_a0;

// For $wr_en.
logic L0_wr_en_a0;

// For $wr_index.
logic [4:0] L0_wr_index_a0;

// For /csr$value.
logic [31:0] Csr_value_n1 [31:0],
             Csr_value_a0 [31:0];

// For /xreg$value.
logic [32-1:0] Xreg_value_n1 [31:0],
               Xreg_value_a0 [31:0];



   // Staging of $commit.
   always_ff @(posedge clk) L0_commit_a1 <= L0_commit_a0;

   // Staging of $instr.
   always_ff @(posedge clk) L0_instr_a1[31:0] <= L0_instr_a0[31:0];

   // Staging of $next_pc.
   always_ff @(posedge clk) L0_next_pc_a1[31:0] <= L0_next_pc_a0[31:0];

   // Staging of $next_state.
   always_ff @(posedge clk) L0_next_state_a1[1:0] <= L0_next_state_a0[1:0];

   // Staging of $passed_cond.
   always_ff @(posedge clk) L0_passed_cond_a1 <= L0_passed_cond_a0;
   always_ff @(posedge clk) L0_passed_cond_a2 <= L0_passed_cond_a1;

   // Staging of $pc.
   always_ff @(posedge clk) L0_pc_a1[31:0] <= L0_pc_a0[31:0];

   // Staging of $reset.
   always_ff @(posedge clk) L0_reset_a1 <= L0_reset_a0;


   //
   // Scope: /csr[31:0]
   //
   for (csr = 0; csr <= 31; csr++) begin : L1gen_Csr
      // Staging of $value.
      always_ff @(posedge clk) Csr_value_a0[csr][31:0] <= Csr_value_n1[csr][31:0];

   end

   //
   // Scope: /xreg[31:0]
   //
   for (xreg = 0; xreg <= 31; xreg++) begin : L1gen_Xreg
      // Staging of $value.
      always_ff @(posedge clk) Xreg_value_a0[xreg][32-1:0] <= Xreg_value_n1[xreg][32-1:0];

   end
